config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
     belongs_to :creator, class_name: "User"

     default_scope -> { order(created_at: :desc) }

     validates :creator_id, presence: true
     validates :name, presence: true, length: {minimum: 3 }
     validates :dateofevent, presence: true
     validates :location, presence: true 


end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id"

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


    def index 
        @events = Event.all 
    end 

    def new 
        @event = Event.new
    end 

    def create 
        @event = current_user.events.build(event_params)
        if @event.save
            flash[:success] = "Event created!"
            redirect_to root_url
        else
            render 'new'
        end
    end 

    def show
        @event = Event.find(params[:id])
        @creator = @event.creator
    end 

    private 

        def event_params
            params.require(:event).permit(:name, :description, :dateofevent, :location)
        end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include ApplicationHelper 

    def new 
    end 

    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user
            log_in user
            # remember user
            flash[:success] = "Successfully logged in"
            redirect_to root_url
        else
            flash.now[:danger] = 'No registered user with that email'
            render 'new'
        end
    end 

    def destroy 
        log_out if logged_in?
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



    def new 
        @user = User.new 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "User created successfully."
            redirect_to root_url
          else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
        @events =  @user.events
    end


    private

        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
      @current_user = user
    end
  
    # Remembers a user in a persistent session.
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end
  
  
    # Returns true if the given user is the current user.
    def current_user?(user)
      user == current_user
    end
  
  
    # Returns the user corresponding to the remember token cookie.
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    # Forgets a persistent session.
    def forget(user)
      #user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end
  
    # Logs out the current user.
    def log_out
      forget(current_user)
      session.delete(:user_id)
      @current_user = nil
      flash[:success] = "Succesfuly log out!"
      redirect_to root_url
    end
  
    
  
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_events.html.erb
<li id="event-<%= event.id %>">
  <span class="event"><%= link_to event.creator.name, event.creator %></span>
  <span class="name"><%= event.name %></span>
  <span class="description"><%= event.description %></span>
  <span class="dateofevent"><%= event.dateofevent %></span>
  <span class="location"><%= event.location %></span>


  <span class="timestamp">
    Posted <%= time_ago_in_words(event.created_at) %> ago.
  </span>
</li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
        The form contains <%= pluralize(@event.errors.count, "error") %>.
        </div>
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

  
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  
    <%= f.label :dateofevent %>
    <%= f.text_field :dateofevent, class: 'form-control' %>
  
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
  

app/views/events/index.html.erb
<div class="row">
<aside class="col-md-12">
<section class="user_info">

<h1>All Events (<%= @events.count %>)<span><%= link_to "Create new", new_event_path %></span></h1>

  <div class="events">
      <% @events.each do |event| %>
      <div class="event">
          <span class="name"><%= link_to event.name%></span>
          <span><%= event.creator.name %></span>
          <span class="description"><%= event.description %></span>
          <span class="dateofevent">Date: <%= event.dateofevent %></span>
          <span class="location">Location: <%= event.location %></span>


          <span class="timestamp">
              Posted <%= time_ago_in_words(event.created_at) %> ago.
          </span>
      </div>
      <% end %>
  </div>

  </section>
  </aside>
</div>

 

app/views/events/new.html.erb
<h1>New Event</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <aside class="col-md-12">
    <section class="user_info">
      <h1>
        <%= @event.creator.name %>
      </h1>
      
      
      
    </section>
  </aside>
</div>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Private-Events", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_url %></li>
        <% if current_user %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="col-md-6 col-md-offset-3">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: @user %>
  
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
  

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-12">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
      
      <% if @user.events.any? %>
        <h3>My Events (<%= @user.events.count %>)</h3>
        <div class="events">
            <% @user.events.each do |event| %>
            <div class="event">
                <span class="name"><%= link_to event.name, event_path %></span>
                <span class="description"><%= event.description %></span>
                <span class="dateofevent">Date: <%= event.dateofevent %></span>
                <span class="location">Location: <%= event.location %></span>


                <span class="timestamp">
                    Posted <%= time_ago_in_words(event.created_at) %> ago.
                </span>
            </div>
            <% end %>
        </div>
      <% end %>
      
    </section>
  </aside>
</div>